version: '3.8'

networks:
  arcana:

services:

  angular-service: 
    container_name: team10_arcana-frontend
    build: ./Frontend
    # volumes:
    #   - '~/arcana-frontend:/app'
    ports:
      - '4200:4200'
    networks:
      - arcana

  flask-service:
    container_name: team10_arcana-backend
    build: ./Backend
    # volumes:
    #   - '~/arcana-backend:/app'
    ports:
      - '7200:7200'
    networks:
      - arcana

  mongodb:
    container_name: team10_arcana-mongodb
    image: mongodb/mongodb-community-server:latest
    expose:
      - 27017
    ports:
      - '27017:27017'
    networks:
      - arcana
